spring :
  datasource :
    driver-class-name : com.mysql.cj.jdbc.Driver
    username : root
    password : root
    url : jdbc:mysql://root:root@localhost:3306/fmsdb
  mail :
    host : smtp.gmail.com
    port : 465
    username : dummytummy678@gmail.com 
    password : dummytummy123
    protocol : smtps
    properties : 
      mail :
        smtp :
          auth : true
          connectiontimeout : 5000
          timeout : 5000
          writetimeout : 5000
          starttls :
            enable : true

server :
  servlet :
    context-path : /fms
    
fms :
  participation :
    type :
      registered : Registered
      attended : Participated
      unattended : Not Participated
      unregistered : UnRegistered
  import :
    file-path :  
      event-info-list : F:\Training\Excel\OutReach-Event Summary.xlsx
      volunteer-attended-list : F:\Training\Excel\OutReach-Event Information.xlsx
      volunteer-unattended-list : F:\Training\Excel\Voluntary Enrollment Details - Not Attended.xlsx
      volunteer-unregistered-list :  F:\Training\Excel\Voluntary Enrollment Details - UnRegistered.xlsx     
