spring :
  datasource :
    driver-class-name : com.mysql.cj.jdbc.Driver
    username : root
    password : root
    url : jdbc:mysql://root:root@localhost:3306/fmsdb

server :
  servlet :
    context-path : /fms
